# Generated by Django 4.2.27 on 2025-12-14 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('summary', 'Summary'), ('notes', 'Study Notes'), ('flashcards', 'Flashcards'), ('quiz', 'Quiz')], max_length=50)),
                ('content', models.JSONField(help_text='The structured content generated (e.g. JSON)')),
                ('model_version', models.CharField(default='gemini-1.5-flash', max_length=50)),
                ('token_usage', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to='ingestion.job')),
            ],
            options={
                'db_table': 'generated_content',
                'indexes': [models.Index(fields=['job', 'type'], name='generated_c_job_id_b058f7_idx')],
                'unique_together': {('job', 'type')},
            },
        ),
    ]
