# Generated by Django 6.0 on 2025-12-10 00:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('storage_url', models.TextField()),
                ('material_types', models.JSONField(default=list, help_text='Types of materials to generate: summary, notes, flashcards, quiz')),
                ('options', models.JSONField(blank=True, default=dict, help_text='Optional parameters like summary_length, flashcard_count, etc.')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('transcribing', 'Transcribing'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('transcription_id', models.UUIDField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='jobs_user_id_13cde9_idx'), models.Index(fields=['status', '-created_at'], name='jobs_status_70b954_idx')],
            },
        ),
    ]
