# Generated by Django 4.2.27 on 2025-12-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='transcription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
